/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 */
import { MotiaStream } from 'motia'

declare module 'motia' {
  interface Streams {}

  interface Enqueues {
    'google.index': unknown
    'indexnow.index': unknown
    'url.submitted': unknown
    'submission.retry': unknown
    'submission.complete': unknown
  }
}
